title: Stuart Kennedy
url: 'https://iamstu.art'
theme_skin: ceramic
chrome_mobile_color:


sass:
  sass_dir: _sass
  style: compressed

compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

port: 4000
host: 0.0.0.0
safe: false
